import { ASSETS } from './assets.const'
const businessDetails = {
  name: 'Bite Buddy',
  description: 'A Symphony of Exquisite Tastes, Where Every Bite Tells an Enchanting Story.',
  banner: ASSETS.IMAGES.BANNER,
  facebookLink: 'https://facebook.com',
  appStoreLink: 'https://appstore.com',
  googlePlayLink: 'https://google.com',
  streetAddress: '30-32 Fifth Avenue, Black Town',
  city: 'Sydney',
  state: 'New South Wales',
  zipCode: '2148',
  storePhoneNumber: '0420817538',
  businessEmail: 'sjeewan53@gmail.com',
  openTime: '10:00 am',
  closeTime: '05:00 pm',
}

const todaysSpecial = [
  {
    posItemID: 1,
    item: 'Pizza',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 0,
    netPrice: 10,
    imageUrl: ASSETS.IMAGES.PIZZA,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 2,
    item: 'Pizza',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 0,
    netPrice: 10,
    imageUrl: ASSETS.IMAGES.PIZZA,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 3,
    item: 'Pizza',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 0,
    netPrice: 10,
    imageUrl: ASSETS.IMAGES.PIZZA,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 4,
    item: 'Pizza',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 0,
    netPrice: 10,
    imageUrl: ASSETS.IMAGES.PIZZA,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 5,
    item: 'Pizza',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 0,
    netPrice: 10,
    imageUrl: ASSETS.IMAGES.PIZZA,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 6,
    item: 'Pizza',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 0,
    netPrice: 10,
    imageUrl: ASSETS.IMAGES.PIZZA,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 7,
    item: 'Pizza',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 0,
    netPrice: 10,
    imageUrl: ASSETS.IMAGES.PIZZA,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 8,
    item: 'Pizza',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 0,
    netPrice: 10,
    imageUrl: ASSETS.IMAGES.PIZZA,
    likes: 20,
    disLikes: 6,
  },
]

const allDeals = [
  {
    posItemID: 1,
    item: 'Mo:Mo',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 2,
    netPrice: 8,
    imageUrl: ASSETS.IMAGES.MOMO,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 2,
    item: 'Mo:Mo',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 2,
    netPrice: 8,
    imageUrl: ASSETS.IMAGES.MOMO,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 3,
    item: 'Mo:Mo',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 2,
    netPrice: 8,
    imageUrl: ASSETS.IMAGES.MOMO,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 4,
    item: 'Mo:Mo',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 2,
    netPrice: 8,
    imageUrl: ASSETS.IMAGES.MOMO,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 5,
    item: 'Mo:Mo',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 2,
    netPrice: 8,
    imageUrl: ASSETS.IMAGES.MOMO,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 6,
    item: 'Mo:Mo',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 2,
    netPrice: 8,
    imageUrl: ASSETS.IMAGES.MOMO,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 7,
    item: 'Mo:Mo',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 2,
    netPrice: 8,
    imageUrl: ASSETS.IMAGES.MOMO,
    likes: 20,
    disLikes: 6,
  },
  {
    posItemID: 8,
    item: 'Mo:Mo',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 10,
    discount: 2,
    netPrice: 8,
    imageUrl: ASSETS.IMAGES.MOMO,
    likes: 20,
    disLikes: 6,
  }
]

export const PSEUDO_API = {
  businessDetails,
  todaysSpecial,
  allDeals
}
